### ISSUE TITLE
Improving the README

### ISSUE THREAD

**Issue by nikhilkalburgi** [nikhilkalburgi/ftp-for-node#1]
I want the readme to be improved

**Comment by KunjShah95** [comment]
FTP for Node.js

[![GitHub Issues](https://img.shields.io/github/issues/nikhilkalburgi/ftp-for-node)](https://github.com/nikhilkalburgi/ftp-for-node/issues)
[![License](https://img.shields.io/github/license/nikhilkalburgi/ftp-for-node)](LICENSE)

A simple, efficient FTP client for Node.js that enables file transfers, management, and server interaction using the FTP protocol. This project aims to provide a straightforward way to connect, upload, download, and manage files on FTP servers.



 🚀 Features

- Easy FTP integration: Simplifies interaction with FTP servers in Node.js.
- File operations: Upload, download, and manage files efficiently.
- Asynchronous API: Fully asynchronous for non-blocking I/O.
- **Support for multiple connections: Handle multiple FTP connections simultaneously.
- Error handling: Provides detailed error reports for debugging.

 📦 Installation

```bash
npm install ftp-for-node
```

🔧 Usage

Here's a quick example of how to use `ftp-for-node`:

```javascript
const FTPClient = require('ftp-for-node');

// Initialize FTP client
const client = new FTPClient({
  host: 'ftp.example.com',
  port: 21,
  user: 'username',
  password: 'password',
});

// Connect to the FTP server
client.connect()
  .then(() => {
    // Upload a file
    return client.upload('/local/path/to/file.txt', '/remote/path/file.txt');
  })
  .then(() => {
    console.log('File uploaded successfully!');
    // Download a file
    return client.download('/remote/path/file.txt', '/local/path/to/download/file.txt');
  })
  .then(() => {
    console.log('File downloaded successfully!');
    client.disconnect(); // Close the connection
  })
  .catch((err) => {
    console.error('FTP Error:', err);
  });
```

### Available Methods

- `connect()`: Establishes a connection to the FTP server.
- `upload(localPath, remotePath)`: Uploads a file to the remote FTP server.
- `download(remotePath, localPath)`: Downloads a file from the FTP server.
- `delete(remotePath)`: Deletes a file from the FTP server.
- `disconnect()`: Disconnects from the FTP server.

---

## 📖 Documentation

For a full list of available methods and advanced usage, please check out the [API Documentation](https://github.com/nikhilkalburgi/ftp-for-node/wiki).

---

## 🤝 Contributing

We welcome contributions! Please check out our [Contribution Guidelines](https://github.com/nikhilkalburgi/ftp-for-node/blob/main/CONTRIBUTING.md) for more information.

### How to Contribute:
1. Fork the repo.
2. Create a new branch: `git checkout -b feature-branch`
3. Make your changes.
4. Commit your changes: `git commit -m 'Add some feature'`
5. Push to the branch: `git push origin feature-branch`
6. Open a Pull Request.



🐛 Issues

Have a bug or an issue? Please check out the [issues page](https://github.com/nikhilkalburgi/ftp-for-node/issues) or open a new issue with a detailed description of the problem.



 📄 License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

---

 💬 Support

If you need help, feel free to reach out or open an issue.

Happy coding!

---

**Comment by nikhilkalburgi** [comment]
Hi @KunjShah95 ,

I appreciate your interest in contributing to this repo. I have recently merged some changes related to the readme. I would like you to do some enhancements on that. I will accept it for hacktoberfest. 

There are some unnecessary parts in the readme yet. See if you can improve it.

**Comment by nikhilkalburgi** [comment]
Go ahead and make a PR. lets discuss it in the PR itself

**Comment by KunjShah95** [comment]
SURE I WOULD LIKE TO CONTRIBUTE BUT IS THE README CORRECT AND UPDATED U WANT

**Comment by KunjShah95** [comment]
kindly check i have sent u the pull request for the readme file
